### ISSUE TITLE
Fails at edge cases

### ISSUE THREAD

**Issue by luokar** [bebound/Pixiv#6] opened 2016-11-14 13:56 UTC
This program can't handle http://www.pixiv.net/member_illust.php?mode=medium&illust_id=8070375
and keep retrying.

**Comment by bebound** [comment] 2016-11-14 15:44
Hmm, can you provide more information, what did you do?

**Comment by luokar** [comment] 2016-11-14 16:04
I run `python pixiv.py 73286` to download しぶぞー's illustrations. and when it runs into illust_id=8070375, the program keeps complaining "404 => 8070375 download error, retry"

**Comment by bebound** [comment] 2016-11-14 16:37
I guess I fixed it, try the latest version. :)

**Comment by luokar** [comment] 2016-11-15 05:02
Yes, I think the problem is resolved. But it displays a strange warning, I guess it is harmless?
`pixiv.py:147: SyntaxWarning: name '_finished_download' is assigned to before global declaration`

**Comment by bebound** [comment] 2016-11-15 05:48
That's a small bug, I'll fix it.

Thanks for your report
Get Outlook for iOS

On Tue, Nov 15, 2016 at 1:02 PM +0800, "luokar" notifications@github.com wrote:

Yes, I think the problem is resolved. But it displays a strange warning, I guess it is harmless?

pixiv.py:147: SyntaxWarning: name '_finished_download' is assigned to before global declaration

**Closed as completed** 2016-11-15 05:53 UTC
